name: Lab 7
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Build with Gradle
        run: ./gradlew build
        
      - name: Run backend tests
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: ./gradlew test

      - name: Generate JaCoCo Coverage Report
        run: ./gradlew jacocoTestReport
